<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-FSHBSE6" name="Command line test" tests="8" failures="1" timestamp="7 Jun 2022 08:50:56 GMT" time="1.171" errors="0">
  <testcase name="testlogin" time="0.531" classname="JustTest.DataProviderDemo"/>
  <testcase name="testlogin" time="0.065" classname="JustTest.DataProviderDemo"/>
  <testcase name="testlogin" time="0.097" classname="JustTest.DataProviderDemo"/>
  <testcase name="getAllLessUser" time="0.062" classname="JustTest.UserTestDemo">
    <failure type="java.lang.AssertionError" message="expected [success] but found [未认证，请先登录]">
        <![CDATA[java.lang.AssertionError: expected [success] but found [未认证，请先登录]
	at JustTest.UserTestDemo.getAllLessUser(UserTestDemo.java:150)
	at testngRun.main(testngRun.java:11)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- getAllLessUser -->
  <testcase name="login_postmanchange" time="0.091" classname="JustTest.UserTestDemo"/>
  <testcase name="password" time="0.062" classname="JustTest.UserTestDemo"/>
  <testcase name="login" time="0.175" classname="JustTest.UserTestDemo"/>
  <testcase name="user_list_user" time="0.068" classname="JustTest.UserTestDemo"/>
</testsuite> <!-- Command line test -->
